[Diretorios]

Nome        =  TEST_TAB_DEBUG
PathDefault =  ..\..\include
err         =  ..\err
obj         =  ..\obj
c           =  ..\..\src
h           =  ..\..\include
def         =  ..\..\tabelas
tab         =  ..\tabs
inc         =  ..\tabs

[Modulos]
TESTTAB 	/D_DEBUG
TABULEIRO	/D_DEBUG
CASA  		/D_DEBUG
PECA 		/D_DEBUG
LISTA 		/D_DEBUG
VALIDA_MOV 	/D_DEBUG

[BuildInicio]
/OUT:TEST_TAB_DEBUG.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
..\..\lib\ArcaboucoTeste.lib

[Fim]
