[Diretorios]

Nome        =  TEST_LIS
PathDefault =  ..\..\include
err         =  ..\err
obj         =  ..\obj
c           =  ..\..\src
h           =  ..\..\include
def         =  ..\..\tabelas
tab         =  ..\tabs
inc         =  ..\tabs

[Modulos]
TESTLIS       /D_DEBUG
LISTA         /D_DEBUG

[BuildInicio]
/OUT:TEST_LIS.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
..\..\lib\ArcaboucoTeste.lib

[Fim]
